spring:
  application:
    name: mindbloom

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: create


  datasource:
    url: jdbc:mysql://localhost:3306/db_mindbloom_core
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver