spring:
  application:
    name: mindbloom
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  datasource:
    url: jdbc:mysql://localhost:3306/db_mindbloom_core
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

jwt:
  token:
    secretKey: "aclkLc48O1xMi4eurekaCJJ426phEa1Wc4mindbloom"